<?php
/******************************************************************************
 * NINA VIỆT NAM
 * Email: nina@nina.vn
 * Website: nina.vn
 * Version: 1.1.1 
 * Date 18-09-2024
 * Đây là tài sản của CÔNG TY TNHH TM DV NINA. Vui lòng không sử dụng khi chưa được phép.
 */

return [
    'logo' => [
        'title_main' => "Logo",
        'kind' => 'static',
        'title' => true,
        'desc' => false,
        'desc_cke' => false,
        'link' => true,
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 185,
        'height' => 57,
        'thumb' => '185x57x1',
    ],
    'favicon' => [
        'title_main' => "Favicon",
        'kind' => 'static',
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 48,
        'height' => 48,
        'thumb' => '48x48x1',
    ],
    'slide' => [
        'title_main' => "Slideshow",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 5,
        'images' => true,
        'show_images' => true,
        'gallery' => true,
        'link' => true,
        'name' => true,
        'desc' => false,
        'desc_cke' => false,
        'width' => 1366,
        'height' => 620,
        'thumb' => '1366x620x1',
        'thumb2' => '500x219x1',
    ],
    'slide-m' => [
        'title_main' => "Slideshow mobile",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 5,
        'images' => true,
        'show_images' => true,
        'gallery' => true,
        'link' => true,
        'name' => true,
        'desc' => false,
        'desc_cke' => false,
        'width' => 450,
        'height' => 650,
        'thumb' => '450x650x1',
    ],
    'social' => [
        'title_main' => "Social left",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 4,
        'show_images' => true,
        'images' => true,
        'avatar' => true,
        'link' => true,
        'name' => true,
        'desc' => false,
        'width' => 40,
        'height' => 40,
        'thumb' => '40x40x2',
    ],
    'mangxahoi1' => [
        'title_main' => "Mạng xã hội footer",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 4,
        'show_images' => true,
        'images' => true,
        'avatar' => true,
        'link' => true,
        'name' => true,
        'desc' => false,
        'width' => 20,
        'height' => 20,
        'thumb' => '20x20x2',
    ],
    'doitac' => [
        'title_main' => "Doanh nghiệp đã sử dụng",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 4,
        'show_images' => true,
        'images' => true,
        'avatar' => true,
        'link' => true,
        'name' => true,
        'desc' => false,
        'width' => 168,
        'height' => 122,
        'thumb' => '168x122x1',
    ],
    'watermark_product' => [
        'title_main' => "Đóng dấu",
        'kind' => 'static',
        'watermark' =>true,
        'desc' => false,
        'title' => false,
        'desc_cke' => false,
        'link' => false,
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 70,
        'height' => 70,
        'thumb' => '70x70x1',
    ],
    'lien-ket' => [
        'title_main' => "Liên kết shop",
        'kind' => 'album',
        'number' => 1,
        'status' => ["hienthi" => "Hiển thị"],
        'link' => true,
        'name' => true,
    ],
    'quang-cao' => [
        'title_main' => "Quảng cáo",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 2,
        'show_images' => true,
        'images' => true,
        'avatar' => true,
        'link' => true,
        'name' => true,
        'desc' => true,
        'width' => 600,
        'height' => 324,
        'thumb' => '600x324x1',
    ],
    'banner-qc' => [
        'title_main' => "Banner quảng cáo",
        'kind' => 'static',
        'title' => true,
        'link' => true,
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 1366,
        'height' => 350,
        'thumb' => '1366x350x1',
    ],
    'video-home' => [
        'title_main' => "Video",
        'kind' => 'static',
        'title' => true,
        'link' => true,
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 1366,
        'height' => 597,
        'thumb' => '1366x597x1',
    ]
];